import random
from random import choice
first_fun = [
    "Holy Flamming",
    "Giant Death",
    "Terrible",
    "Unholy Freezing",
    "Anti-telaharsec",
    "Tiny",
    "Magic Flying",
    "Healing",
    "Unholy"
    "Screaming",
    "Vorpal",
    "Laser-Powered",
    "Goblin-Smashing",
    "Holy",
    "Submersable",
    "Annoying",
    "Boring",
    "Singing",
    "Heavy Metal",
    "Glory",
    "Galactic",
    "Astral",
    "Golden",
    "Evil",
    "Cosmic",
    "Thundering",
    "Laser",
    "Amazing",
    "Immortal",
    "Giant",
    "Doomed",
    "Laser-shooting",
    "Thunder-Striking",
    "Wizard-Thrashing",
    "Dark Matter",
    "Ultimate",
    "Tyannical",
    "Monstrous",
    "Mighty",
    "Slashing",
    "Wise",
    "All-Seeing",
    "Shining",
    "Magic",
    "Toy",
    "Invisible",
]
second_fun = [
    "Chili Peppers",
    "Nevada",
    "Scratching People",
    "Bitterness",
    "Chasing Cats",
    "Sillyness",
    "Summoning Demons",
    "Reno",
    "Fallon",
    "Fernley",
    "Smashing Goblins",
    "Thrashing Evil Wizards",
    "Chrushing Darklords",
    "Fife",
    "Dundee",
    "Dunkeld",
    "The River Tay",
    "Fighting Trolls",
    "Glory",
    "Justice",
    "Evil",
    "Chaos",
    "Crail",
    "Making Us Laugh",
    "Paris",
    "Shopping",
    "Traveling Space",
    "Fighting Space Battles",
    "Nuclear Justice",
    "Recording Information",
    "All-Seeing",
    "Sailing",
    "Unholy Cosmic Frost",
    "Glorius Hair",
    "Endless Energy",
    "Holding Picture",
    "Messyness",
    "Dispair",
    "Eat Your Face",
    "Flying High Into Space",
    "Happy Funness",
    "Egg-Lofting",
    "Blowing Up The Death Star",
    "Making Things Go Kaboom",
    "Flame",
    "Silver Springs",
    "Carson City",
    "Madness",
    "Cleaving Castles",
    "Wacking",
    "Lake Tahoe",
    "The Truckee River",
]
print("This a Python program written to make ridiculous names for anything you can think of. Your math book? The Galactic Math Book of Reno!")
print("Your phone? It's the Evil Phone of Eat Your Face! Your Keyboard? The Annoying Keyboard of Wacking! The names get ridiculous!")
print("Warning: there may or may not be small amounts of funny references in here. Use at your own risk.")
word = input("what do you want a name for: ")
start = choice(first_fun)
end = choice(second_fun)
the = random.randint(1, 3)
if the == 1:
    print("The {} {} of {}.".format(start, word, end))
elif the == 2:
    print("The {} {}.".format(start, word))
elif the == 3:
    print("The {} of {}.".format(word, end))


